### ISSUE TITLE
小bug,  2.0版本 ChatClient.php  命名空间错误

### ISSUE THREAD

**Issue by accpdyk** [cdcchen/wechat-client#1]
<pre>
namespace cdcchen\wechat\qy\chat;
</pre>

应该改成

<pre>
namespace cdcchen\wechat\qy;
</pre>

**Comment by cdcchen** [comment]
#45630cdb52a0e65032d33d44e0140e46e595e3ba

**Comment by cdcchen** [comment]
Fixed by commit [`#45630cd`](//github.com/cdcchen/wechat-client/commit/45630cdb52a0e65032d33d44e0140e46e595e3ba)
